services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
    container_name: redpanda
    networks:
      - monitor-net
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092
    expose:
      - 9644

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    networks:
      - monitor-net
    ports:
    - 3000:3000
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    expose:
      - 9090
    networks:
      - monitor-net
    volumes:
      - type: bind
        source: ./prometheus-data
        target: /etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    labels:
      org.label-schema.group: "monitoring"

networks:
  monitor-net:
    driver: bridge
